const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors()); app.use(express.json());
app.post('/api/generate', async (req,res)=>{ const data = req.body; // In production call OpenAI here
  // Mock response
  res.json({title: data.name + "'s Portfolio", about: 'This portfolio was generated by AI.'});
});
app.listen(5000, ()=>console.log('Server on 5000'));